# Generated by Django 5.1.3 on 2025-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sid",
                    models.CharField(
                        help_text="Organization SID (e.g., FAROUT)",
                        max_length=10,
                        unique=True,
                        verbose_name="SID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "archetype",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Archetype"
                    ),
                ),
                (
                    "commitment",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Commitment"
                    ),
                ),
                (
                    "primary_language",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Primary Language"
                    ),
                ),
                (
                    "recruiting",
                    models.BooleanField(default=False, verbose_name="Recruiting"),
                ),
                (
                    "member_count",
                    models.IntegerField(default=0, verbose_name="Member Count"),
                ),
                ("headline", models.TextField(blank=True, verbose_name="Headline")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("history", models.TextField(blank=True, verbose_name="History")),
                ("manifesto", models.TextField(blank=True, verbose_name="Manifesto")),
                ("charter", models.TextField(blank=True, verbose_name="Charter")),
                ("logo_url", models.URLField(blank=True, verbose_name="Logo URL")),
                ("banner_url", models.URLField(blank=True, verbose_name="Banner URL")),
                (
                    "api_data",
                    models.JSONField(blank=True, default=dict, verbose_name="API Data"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        help_text="Star Citizen handle",
                        max_length=100,
                        unique=True,
                        verbose_name="Handle",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="Display Name"),
                ),
                (
                    "rank",
                    models.CharField(blank=True, max_length=100, verbose_name="Rank"),
                ),
                ("stars", models.IntegerField(default=0, verbose_name="Stars")),
                ("avatar_url", models.URLField(blank=True, verbose_name="Avatar URL")),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                (
                    "api_data",
                    models.JSONField(blank=True, default=dict, verbose_name="API Data"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Organization Member",
                "verbose_name_plural": "Organization Members",
                "ordering": ["-stars", "handle"],
                "indexes": [
                    models.Index(
                        fields=["handle"], name="organizatio_handle_ad58be_idx"
                    ),
                    models.Index(
                        fields=["-stars"], name="organizatio_stars_b93a0b_idx"
                    ),
                ],
            },
        ),
    ]
