# Generated by Django 5.1.3 on 2025-11-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("starships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_id",
                    models.CharField(
                        db_index=True,
                        help_text="Discord user ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Display name in organization", max_length=255
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Member biography", null=True
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True,
                        help_text="Avatar image URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Star Citizen character profile image",
                        null=True,
                        upload_to="member_profiles/",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("corporal", "Corporal"),
                            ("sergeant", "Sergeant"),
                            ("lieutenant", "Lieutenant"),
                            ("captain", "Captain"),
                            ("major", "Major"),
                            ("colonel", "Colonel"),
                            ("commander", "Commander"),
                            ("admiral", "Admiral"),
                            ("fleet_admiral", "Fleet Admiral"),
                        ],
                        db_index=True,
                        default="private",
                        help_text="Member rank in organization",
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("member", "Member"),
                            ("admin", "Admin"),
                        ],
                        db_index=True,
                        default="user",
                        help_text="Member role in organization",
                        max_length=20,
                    ),
                ),
                (
                    "squadron",
                    models.CharField(
                        blank=True,
                        help_text="Squadron assignment",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "missions_completed",
                    models.JSONField(
                        blank=True, default=list, help_text="List of completed missions"
                    ),
                ),
                (
                    "trainings_completed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of completed trainings",
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Member statistics (kills, deaths, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "db_table": "members",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["discord_id"], name="members_discord_cac50a_idx"
                    ),
                    models.Index(fields=["rank"], name="members_rank_fdcf38_idx"),
                    models.Index(
                        fields=["display_name"], name="members_display_b066b9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShipOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of ships owned"
                    ),
                ),
                (
                    "acquired_date",
                    models.DateTimeField(auto_now_add=True, help_text="Date acquired"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member who owns the ship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ship_ownerships",
                        to="members.member",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        help_text="Ship owned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="starships.ship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ship Ownership",
                "verbose_name_plural": "Ship Ownerships",
                "db_table": "ship_ownerships",
                "ordering": ["-acquired_date"],
                "unique_together": {("member", "ship")},
            },
        ),
    ]
