#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE farout;
    CREATE DATABASE farout_auth;
    GRANT ALL PRIVILEGES ON DATABASE farout TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE farout_auth TO $POSTGRES_USER;
EOSQL
