# Generated by Django 5.1.3 on 2025-11-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Uploaded profile picture (overrides Discord avatar)",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
