# Generated by Django 5.1.3 on 2025-11-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Manufacturer code (e.g., AEGS)",
                        max_length=10,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("logo_url", models.URLField(blank=True, verbose_name="Logo URL")),
                (
                    "api_id",
                    models.CharField(blank=True, max_length=50, verbose_name="API ID"),
                ),
                (
                    "api_data",
                    models.JSONField(blank=True, default=dict, verbose_name="API Data"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "type",
                    models.CharField(blank=True, max_length=100, verbose_name="Type"),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("vehicle", "Vehicle"),
                            ("snub", "Snub"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("capital", "Capital"),
                        ],
                        default="small",
                        max_length=20,
                        verbose_name="Size",
                    ),
                ),
                (
                    "focus",
                    models.CharField(blank=True, max_length=200, verbose_name="Focus"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "career",
                    models.CharField(blank=True, max_length=100, verbose_name="Career"),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=100, verbose_name="Role"),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Length (m)",
                    ),
                ),
                (
                    "beam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Beam (m)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Height (m)",
                    ),
                ),
                (
                    "mass",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Mass (kg)",
                    ),
                ),
                (
                    "min_crew",
                    models.IntegerField(blank=True, null=True, verbose_name="Min Crew"),
                ),
                (
                    "max_crew",
                    models.IntegerField(blank=True, null=True, verbose_name="Max Crew"),
                ),
                (
                    "cargo_capacity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Cargo Capacity (SCU)"
                    ),
                ),
                (
                    "is_flight_ready",
                    models.BooleanField(default=False, verbose_name="Flight Ready"),
                ),
                (
                    "is_concept",
                    models.BooleanField(default=False, verbose_name="Concept"),
                ),
                (
                    "production_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Production Status"
                    ),
                ),
                (
                    "pledge_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Pledge Price (USD)",
                    ),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="Image URL")),
                ("store_url", models.URLField(blank=True, verbose_name="Store URL")),
                (
                    "api_id",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="API ID"
                    ),
                ),
                (
                    "api_data",
                    models.JSONField(blank=True, default=dict, verbose_name="API Data"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ships",
                        to="starships.manufacturer",
                        verbose_name="Manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ship",
                "verbose_name_plural": "Ships",
                "ordering": ["manufacturer__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShipComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("shield", "Shield"),
                            ("power", "Power Plant"),
                            ("cooler", "Cooler"),
                            ("quantum", "Quantum Drive"),
                            ("fuel", "Fuel Tank"),
                            ("cargo", "Cargo Hold"),
                            ("misc", "Miscellaneous"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "size",
                    models.CharField(blank=True, max_length=10, verbose_name="Size"),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Quantity")),
                (
                    "mount_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Mount Name"
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="Details")),
                (
                    "api_data",
                    models.JSONField(blank=True, default=dict, verbose_name="API Data"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="starships.ship",
                        verbose_name="Ship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ship Component",
                "verbose_name_plural": "Ship Components",
                "ordering": ["ship", "component_type", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="ship",
            index=models.Index(
                fields=["manufacturer", "name"], name="starships_s_manufac_e380d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ship",
            index=models.Index(fields=["type"], name="starships_s_type_450d73_idx"),
        ),
        migrations.AddIndex(
            model_name="ship",
            index=models.Index(fields=["size"], name="starships_s_size_16a87f_idx"),
        ),
        migrations.AddIndex(
            model_name="ship",
            index=models.Index(
                fields=["is_flight_ready"], name="starships_s_is_flig_25ccb7_idx"
            ),
        ),
    ]
