# Generated by Django 5.1.3 on 2025-11-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=300, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "response_sent",
                    models.BooleanField(default=False, verbose_name="Response Sent"),
                ),
                (
                    "response_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Response Sent At"
                    ),
                ),
                (
                    "is_spam",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Marked as Spam"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "db_table": "contact_submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "status"],
                        name="contact_sub_created_32ba85_idx",
                    ),
                    models.Index(fields=["email"], name="contact_sub_email_903821_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InternalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_id",
                    models.IntegerField(db_index=True, verbose_name="Sender User ID"),
                ),
                (
                    "sender_name",
                    models.CharField(max_length=200, verbose_name="Sender Name"),
                ),
                (
                    "recipient_id",
                    models.IntegerField(
                        db_index=True, verbose_name="Recipient User ID"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=200, verbose_name="Recipient Name"),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "parent_message_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of parent message for threading",
                        null=True,
                        verbose_name="Parent Message ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "is_deleted_by_sender",
                    models.BooleanField(
                        default=False, verbose_name="Deleted by Sender"
                    ),
                ),
                (
                    "is_deleted_by_recipient",
                    models.BooleanField(
                        default=False, verbose_name="Deleted by Recipient"
                    ),
                ),
                (
                    "is_system_message",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="System Message"
                    ),
                ),
                (
                    "is_announcement",
                    models.BooleanField(default=False, verbose_name="Announcement"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Sent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Message",
                "verbose_name_plural": "Internal Messages",
                "db_table": "internal_messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_id", "-created_at"],
                        name="internal_me_recipie_84589d_idx",
                    ),
                    models.Index(
                        fields=["sender_id", "-created_at"],
                        name="internal_me_sender__6dc677_idx",
                    ),
                    models.Index(
                        fields=["recipient_id", "is_read"],
                        name="internal_me_recipie_796a12_idx",
                    ),
                ],
            },
        ),
    ]
