# Generated by Django 5.1.3 on 2025-11-12 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Squadron",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Squadron Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "callsign",
                    models.CharField(
                        help_text="Squadron callsign/code (e.g., ALPHA, BRAVO)",
                        max_length=50,
                        unique=True,
                        verbose_name="Callsign",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "motto",
                    models.CharField(blank=True, max_length=200, verbose_name="Motto"),
                ),
                (
                    "focus",
                    models.CharField(
                        choices=[
                            ("combat", "Combat Operations"),
                            ("exploration", "Exploration"),
                            ("trading", "Trading & Commerce"),
                            ("mining", "Mining Operations"),
                            ("security", "Security & Escort"),
                            ("support", "Support & Logistics"),
                            ("mixed", "Mixed Operations"),
                        ],
                        default="mixed",
                        max_length=50,
                        verbose_name="Focus",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "is_recruiting",
                    models.BooleanField(default=False, verbose_name="Recruiting"),
                ),
                (
                    "max_members",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of members (leave blank for unlimited)",
                        null=True,
                        verbose_name="Max Members",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, verbose_name="Logo URL")),
                (
                    "color_code",
                    models.CharField(
                        default="#55E6A5",
                        help_text="Hex color code for squadron (e.g., #55E6A5)",
                        max_length=7,
                        verbose_name="Color Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "commander",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commanded_squadrons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Commander",
                    ),
                ),
            ],
            options={
                "verbose_name": "Squadron",
                "verbose_name_plural": "Squadrons",
                "db_table": "squadrons",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SquadronMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("lead", "Squad Lead"),
                            ("officer", "Officer"),
                            ("specialist", "Specialist"),
                        ],
                        default="member",
                        max_length=50,
                        verbose_name="Role",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Joined"),
                ),
                (
                    "left_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Left"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "squadron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="squadron.squadron",
                        verbose_name="Squadron",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squadron_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Squadron Member",
                "verbose_name_plural": "Squadron Members",
                "db_table": "squadron_members",
                "ordering": ["squadron", "-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["squadron", "is_active"],
                        name="squadron_me_squadro_34f7f5_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="squadron_me_user_id_250c9c_idx",
                    ),
                ],
                "unique_together": {("squadron", "user")},
            },
        ),
    ]
