# Generated by Django 5.1.3 on 2025-11-12 12:18

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "blog_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "blog_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(help_text="Blog post title", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug", max_length=255, unique=True
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(help_text="Rich text content (HTML)"),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short excerpt for previews",
                        max_length=500,
                    ),
                ),
                (
                    "feature_image",
                    models.URLField(
                        blank=True,
                        help_text="Featured image URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Is post published?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Post author",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Post category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Post tags",
                        related_name="posts",
                        to="blog.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "db_table": "blog_posts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="blog_posts_slug_b4ca25_idx"),
                    models.Index(
                        fields=["published", "-created_at"],
                        name="blog_posts_publish_1bdacf_idx",
                    ),
                ],
            },
        ),
    ]
