# Generated by Django 5.1.3 on 2025-11-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_add_categories_tags_excerpt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="excerpt",
        ),
    ]
