# Generated by Django 5.1.3 on 2025-11-11 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("starships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Custom ship name (optional)",
                        max_length=200,
                        verbose_name="Custom Name",
                    ),
                ),
                (
                    "purchased_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Purchased Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pledged", "Pledged"),
                            ("loaned", "On Loan"),
                            ("sold", "Sold"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_available_for_missions",
                    models.BooleanField(
                        default=False, verbose_name="Available for Missions"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_ships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fleet_instances",
                        to="starships.ship",
                        verbose_name="Ship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fleet Ship",
                "verbose_name_plural": "Fleet Ships",
                "ordering": ["ship__manufacturer__name", "ship__name"],
                "indexes": [
                    models.Index(
                        fields=["owner", "status"],
                        name="fleet_fleet_owner_i_cf29b5_idx",
                    ),
                    models.Index(
                        fields=["ship", "status"], name="fleet_fleet_ship_id_ed29d7_idx"
                    ),
                ],
            },
        ),
    ]
